//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by slsvcutil, version 4.0.50826.0
// 
namespace ServiceReference.ERP.Medico.Web.ERPMedicoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agendamento", Namespace="http://schemas.datacontract.org/2004/07/ERP.Medico.Web.Models")]
    public partial class Agendamento : object
    {
        
        private System.DateTime DataField;
        
        private System.TimeSpan HoraField;
        
        private System.DateTime HorarioField;
        
        private System.Guid IdField;
        
        private int MedicoIdField;
        
        private string NomePacienteField;
        
        private int PacienteIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Hora
        {
            get
            {
                return this.HoraField;
            }
            set
            {
                this.HoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Horario
        {
            get
            {
                return this.HorarioField;
            }
            set
            {
                this.HorarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MedicoId
        {
            get
            {
                return this.MedicoIdField;
            }
            set
            {
                this.MedicoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomePaciente
        {
            get
            {
                return this.NomePacienteField;
            }
            set
            {
                this.NomePacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PacienteId
        {
            get
            {
                return this.PacienteIdField;
            }
            set
            {
                this.PacienteIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService")]
    public interface ERPMedicoService
    {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ERPMedicoService/GetAgendamentosMedico", ReplyAction="urn:ERPMedicoService/GetAgendamentosMedicoResponse")]
        System.IAsyncResult BeginGetAgendamentosMedico(int medicoId, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] EndGetAgendamentosMedico(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ERPMedicoService/GetAgendamentosMedicoData", ReplyAction="urn:ERPMedicoService/GetAgendamentosMedicoDataResponse")]
        System.IAsyncResult BeginGetAgendamentosMedicoData(int medicoId, System.DateTime data, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] EndGetAgendamentosMedicoData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ERPMedicoServiceChannel : ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAgendamentosMedicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public GetAgendamentosMedicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAgendamentosMedicoDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public GetAgendamentosMedicoDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ERPMedicoServiceClient : System.ServiceModel.ClientBase<ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService>, ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService
    {
        
        private BeginOperationDelegate onBeginGetAgendamentosMedicoDelegate;
        
        private EndOperationDelegate onEndGetAgendamentosMedicoDelegate;
        
        private System.Threading.SendOrPostCallback onGetAgendamentosMedicoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAgendamentosMedicoDataDelegate;
        
        private EndOperationDelegate onEndGetAgendamentosMedicoDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetAgendamentosMedicoDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ERPMedicoServiceClient()
        {
        }
        
        public ERPMedicoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ERPMedicoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ERPMedicoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ERPMedicoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Net.CookieContainer CookieContainer
        {
            get
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    return httpCookieContainerManager.CookieContainer;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else
                {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAgendamentosMedicoCompletedEventArgs> GetAgendamentosMedicoCompleted;
        
        public event System.EventHandler<GetAgendamentosMedicoDataCompletedEventArgs> GetAgendamentosMedicoDataCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService.BeginGetAgendamentosMedico(int medicoId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetAgendamentosMedico(medicoId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService.EndGetAgendamentosMedico(System.IAsyncResult result)
        {
            return base.Channel.EndGetAgendamentosMedico(result);
        }
        
        private System.IAsyncResult OnBeginGetAgendamentosMedico(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int medicoId = ((int)(inValues[0]));
            return ((ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService)(this)).BeginGetAgendamentosMedico(medicoId, callback, asyncState);
        }
        
        private object[] OnEndGetAgendamentosMedico(System.IAsyncResult result)
        {
            ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] retVal = ((ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService)(this)).EndGetAgendamentosMedico(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAgendamentosMedicoCompleted(object state)
        {
            if ((this.GetAgendamentosMedicoCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAgendamentosMedicoCompleted(this, new GetAgendamentosMedicoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAgendamentosMedicoAsync(int medicoId)
        {
            this.GetAgendamentosMedicoAsync(medicoId, null);
        }
        
        public void GetAgendamentosMedicoAsync(int medicoId, object userState)
        {
            if ((this.onBeginGetAgendamentosMedicoDelegate == null))
            {
                this.onBeginGetAgendamentosMedicoDelegate = new BeginOperationDelegate(this.OnBeginGetAgendamentosMedico);
            }
            if ((this.onEndGetAgendamentosMedicoDelegate == null))
            {
                this.onEndGetAgendamentosMedicoDelegate = new EndOperationDelegate(this.OnEndGetAgendamentosMedico);
            }
            if ((this.onGetAgendamentosMedicoCompletedDelegate == null))
            {
                this.onGetAgendamentosMedicoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAgendamentosMedicoCompleted);
            }
            base.InvokeAsync(this.onBeginGetAgendamentosMedicoDelegate, new object[] {
                        medicoId}, this.onEndGetAgendamentosMedicoDelegate, this.onGetAgendamentosMedicoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService.BeginGetAgendamentosMedicoData(int medicoId, System.DateTime data, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetAgendamentosMedicoData(medicoId, data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService.EndGetAgendamentosMedicoData(System.IAsyncResult result)
        {
            return base.Channel.EndGetAgendamentosMedicoData(result);
        }
        
        private System.IAsyncResult OnBeginGetAgendamentosMedicoData(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int medicoId = ((int)(inValues[0]));
            System.DateTime data = ((System.DateTime)(inValues[1]));
            return ((ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService)(this)).BeginGetAgendamentosMedicoData(medicoId, data, callback, asyncState);
        }
        
        private object[] OnEndGetAgendamentosMedicoData(System.IAsyncResult result)
        {
            ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] retVal = ((ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService)(this)).EndGetAgendamentosMedicoData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAgendamentosMedicoDataCompleted(object state)
        {
            if ((this.GetAgendamentosMedicoDataCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAgendamentosMedicoDataCompleted(this, new GetAgendamentosMedicoDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAgendamentosMedicoDataAsync(int medicoId, System.DateTime data)
        {
            this.GetAgendamentosMedicoDataAsync(medicoId, data, null);
        }
        
        public void GetAgendamentosMedicoDataAsync(int medicoId, System.DateTime data, object userState)
        {
            if ((this.onBeginGetAgendamentosMedicoDataDelegate == null))
            {
                this.onBeginGetAgendamentosMedicoDataDelegate = new BeginOperationDelegate(this.OnBeginGetAgendamentosMedicoData);
            }
            if ((this.onEndGetAgendamentosMedicoDataDelegate == null))
            {
                this.onEndGetAgendamentosMedicoDataDelegate = new EndOperationDelegate(this.OnEndGetAgendamentosMedicoData);
            }
            if ((this.onGetAgendamentosMedicoDataCompletedDelegate == null))
            {
                this.onGetAgendamentosMedicoDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAgendamentosMedicoDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetAgendamentosMedicoDataDelegate, new object[] {
                        medicoId,
                        data}, this.onEndGetAgendamentosMedicoDataDelegate, this.onGetAgendamentosMedicoDataCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state)
        {
            if ((this.OpenCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync()
        {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState)
        {
            if ((this.onBeginOpenDelegate == null))
            {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null))
            {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null))
            {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state)
        {
            if ((this.CloseCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync()
        {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState)
        {
            if ((this.onBeginCloseDelegate == null))
            {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null))
            {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null))
            {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService CreateChannel()
        {
            return new ERPMedicoServiceClientChannel(this);
        }
        
        private class ERPMedicoServiceClientChannel : ChannelBase<ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService>, ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService
        {
            
            public ERPMedicoServiceClientChannel(System.ServiceModel.ClientBase<ServiceReference.ERP.Medico.Web.ERPMedicoService.ERPMedicoService> client) : 
                    base(client)
            {
            }
            
            public System.IAsyncResult BeginGetAgendamentosMedico(int medicoId, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = medicoId;
                System.IAsyncResult _result = base.BeginInvoke("GetAgendamentosMedico", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] EndGetAgendamentosMedico(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] _result = ((ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[])(base.EndInvoke("GetAgendamentosMedico", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAgendamentosMedicoData(int medicoId, System.DateTime data, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[2];
                _args[0] = medicoId;
                _args[1] = data;
                System.IAsyncResult _result = base.BeginInvoke("GetAgendamentosMedicoData", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] EndGetAgendamentosMedicoData(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[] _result = ((ServiceReference.ERP.Medico.Web.ERPMedicoService.Agendamento[])(base.EndInvoke("GetAgendamentosMedicoData", _args, result)));
                return _result;
            }
        }
    }
}
// Auto generated configuration elements
// Generated client configuration:CustomBinding_ERPMedicoService<>http://ERPMedicoService.svc<>http://localhost:52878/ERPMedicoService.svc
