//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.Medico {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Erp.Medico.Assets.Resources.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um username para esse email já existe. Por favor entre outro email..
        /// </summary>
        public static string CreateUserStatusDuplicateEmail {
            get {
                return ResourceManager.GetString("CreateUserStatusDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username já existe. Por favor entre outro nome de usuário..
        /// </summary>
        public static string CreateUserStatusDuplicateUserName {
            get {
                return ResourceManager.GetString("CreateUserStatusDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cadastro foi cancelado. Por favor verifique e tente novamente. Se o problema persistir, contate o administrador do sistema..
        /// </summary>
        public static string CreateUserStatusFailed {
            get {
                return ResourceManager.GetString("CreateUserStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha incorreto..
        /// </summary>
        public static string ErrorBadUserNameOrPassword {
            get {
                return ResourceManager.GetString("ErrorBadUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cadastro foi feito com sucesso mas houve um problema durante o login: {0}.
        /// </summary>
        public static string ErrorLoginAfterRegistrationFailed {
            get {
                return ResourceManager.GetString("ErrorLoginAfterRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do erro.
        /// </summary>
        public static string ErrorWindowErrorDetails {
            get {
                return ResourceManager.GetString("ErrorWindowErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um erro desconhecido ocorreu. Contate seu administrador para ajuda..
        /// </summary>
        public static string ErrorWindowGenericError {
            get {
                return ResourceManager.GetString("ErrorWindowGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string ErrorWindowTitle {
            get {
                return ResourceManager.GetString("ErrorWindowTitle", resourceCulture);
            }
        }
    }
}
